version: '3.7'

## Usage
## export COUCHDB_USER=admin && export COUCHDB_PASSWORD=admin123
## docker-compose up -f docker-compose-archv3.yml
## cntrl+c to exit
## docker-compose down
## docker volume rm cht-data cht-couchconfig

## docker-compose up
## https://localhost

services:

  couchdb:
    container_name: medic-couchdb
    image: medicmobile/couchdb:2.3.1-test14
    environment:
      COUCHDB_USER: "${COUCHDB_USER:-cht}"
      COUCHDB_PASSWORD: "${COUCHDB_PASSWORD:-cht_password}"
    # https://hub.docker.com/_/couchdb
    volumes:
      - cht-data:/opt/couchdb/data/
      - cht-couchconfig:/opt/couchdb/etc/local.d/
    networks:
      - medic-net

  medic-api:
    container_name: medic-api
    image: medicmobile/medic-api:3.10.0-010520-test3
    environment:
      COUCHDB_SERVICE_NAME: couchdb
      COUCH_NODE_NAME: "couchdb@127.0.0.1"
      COUCHDB_USER: "${COUCHDB_USER:-cht}"
      COUCHDB_PASSWORD: "${COUCHDB_PASSWORD:-cht_password}"
      HORTI_BOOTSTRAP_VERSION: 3.10.0
      NODE_ENV: production
      HAPROXY_SVC: haproxy
    networks:
      - medic-net
    depends_on:
      - haproxy

  medic-sentinel:
    container_name: medic-sentinel
    image: medicmobile/medic-sentinel:3.10.0-010520-test1
    environment:
      COUCHDB_SERVICE_NAME: couchdb
      COUCH_NODE_NAME: "couchdb@127.0.0.1"
      COUCHDB_USER: "${COUCHDB_USER:-cht}"
      COUCHDB_PASSWORD: "${COUCHDB_PASSWORD:-cht_password}"
      HAPROXY_SVC: haproxy
      API_SVC_NAME: medic-api
      NODE_ENV: production
    networks:
      - medic-net
    depends_on:
      - medic-api
    restart: unless-stopped

  horticulturalist:
    container_name: horticulturalist
    image: medicmobile/horticulturalist:dockerize-123120-3
    environment:
      COUCHDB_SERVICE_NAME: couchdb
      COUCH_NODE_NAME: "couchdb@127.0.0.1"
      COUCHDB_USER: "${COUCHDB_USER:-cht}"
      COUCHDB_PASSWORD: "${COUCHDB_PASSWORD:-cht_password}"
      HAPROXY_SVC: haproxy
      API_SVC_NAME: medic-api
    networks:
      - medic-net
    depends_on:
      - medic-api
    restart: unless-stopped

  haproxy:
    container_name: haproxy
    image: medicmobile/haproxy:rc-1.17
    environment:
      COUCHDB_USER: "${COUCHDB_USER:-cht}"
      COUCHDB_PASSWoRD: "${COUCHDB_PASSWORD:-cht_password}"
      COUCHDB_HOST: couchdb
    networks:
      - medic-net
    depends_on:
      - couchdb
    restart: unless-stopped

  nginx:
    container_name: medic-nginx
    image: medicmobile/nginx:3.10.0-slim-01052021-11
    environment:
      CERTIFICATE_MODE: "${CERTIFICATE_MODE:-SELF_SIGNED}"
      CHT_DOMAIN: "${CHT_DOMAIN?CHT_DOMAIN is required}"
      COUNTRY: "${COUNTRY:-US}"
      STATE: "${STATE:-Colorado}"
      LOCALITY: "${LOCALITY:-Denver}"
      ORGANISATION: "${ORGANISATION:-medic}"
      DEPARTMENT: "${DEPARTMENT:-Department of Information Security}"
      COMMON_NAME: "${COMMON_NAME:-test.medic.org}"
      EMAIL: "${EMAIL:-devops@medic.org}"

    volumes:
      - cht-ssl: /root/.acme.sh/
    #  - ./ssl-certificate-key.pem:/etc/nginx/private/key.pem
    #  - ./ssl-certificate.pem:/etc/nginx/private/cert.pem
    networks:
      - medic-net
    depends_on:
      - medic-api
    ports:
      - 80:80
      - 443:443

volumes:
  cht-data:
    name: cht-data
  cht-couchconfig:
    name: cht-couchconfig
  cht-ssl:
    name: cht-ssl

networks:
  medic-net:
    name: medic-net