name: Build and test performance

on: push
  # push:
  #   branches: 
  #     - "performancetotal"

jobs: 
  build:
    uses: ./.github/workflows/build.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{ needs.build.outputs }}
  # tests:
  #   uses: ./.github/workflows/reusable-workflow-example-called.yml
  #   with:
  #     grunt-cmd: ['ci-webdriver-default']
  #   needs: build
  #   name: test reusable
  #   env: inherit

    

  