name: Build and test performance

on: 
  push:
    branches: 
      - performancetotal

jobs: 


  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      pull-requests: write
    
    # with:
    #   config-path: .github/labeler.yml
    #secrets: inherit
    env: inherit

  # test: 
  #   uses: ./.github/workflows/build.yml
  #   env: inherit
  #   name: Blippedy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - id: do-a-thing
  #       run: |
  #         echo "testing these"
  #         echo "${env.COUCH_URL} is here!"
          
         

  
  # tests:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     config-path: .github/labeler.yml
  #   grunt-cmd: ['ci-webdriver-default']
  #   needs: build
  #   name: test reusable
    # env: inherit

    

  